---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-mongo-service1
spec:
  selector:
      matchLabels:
        app: spring-mongo-service1
  replicas: 2
  template:
    metadata:
      labels:
        app: spring-mongo-service1
    spec:
      containers:
        - name: spring-mongo-service1
          image: spring-mongo-service1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8090
          env:
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: password
            - name: MONGO_DB
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf  
                  key: database
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: mongo-conf 
                  key: host
                  